name: Infra Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker-compose.yml'
      - '.env'
      - 'scripts/**'
      - '.github/workflows/build.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Write SSH key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
          chmod 600 private_key
      - name: Deploy
        run: ./deploy.sh
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_KEY: private_key
