name: Infra Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker-compose.yml'
      - '.env'
      - 'scripts/**'
      - '.github/workflows/build.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ "${SERVER_IP}" = "none" ] || [ -z "${SERVER_IP}" ]; then
              echo "🚫 No server IP set. Skipping deploy."
              exit 0
            fi
            cd /path/to/infra-docker-compose
            git pull
            docker-compose pull
            docker-compose up -d
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
