name: Build & Deploy Service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      docker_context:
        required: false
        default: .
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x scripts/deploy-infra.sh

      - name: Write SSH key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
          chmod 600 private_key

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker_context }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:latest

      - name: Deploy
        run: scripts/deploy-infra.sh
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_KEY: private_key
