name: Build & Deploy Service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      docker_context:
        required: false
        default: .
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker_context }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:latest

      - name: SSH deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ "${SERVER_IP}" = "none" ] || [ -z "${SERVER_IP}" ]; then
              echo "🚫 No server IP set. Skipping deploy."
              exit 0
            fi
            cd /path/to/infra-docker-compose
            ./scripts/deploy-service.sh ${{ inputs.service_name }}
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
